spring.application.name=Student_ManagementHiber
spring.datasource.url = jdbc:postgresql://localhost:5432/Student_ManagementHiber
spring.datasource.username = postgres
spring.datasource.password = abhi@123

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
